services:
  # Production run of the Discord bot
  dd-bot-advanced:
    image: anshuljkt1/dd-bot-advanced:latest
    container_name: dd-bot-advanced
    volumes:
      - ./settings:/app/settings/:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped