name: dd-bot
services:
  ddbot:
    container_name: DD_Bot
    volumes:
      - ./settings:/app/settings/:rw
      - /var/run/docker.sock:/var/run/docker.sock
    # image: assaro/ddbot:latest
    image: anshuljkt1/dd-bot-advanced:1.2
    restart: unless-stopped
#     networks:
#       - swagSSL
# networks:
#   swagSSL:
#     external: true