services:
  dd-bot-advanced:
    container_name: dd-bot-advanced
    volumes:
      - ./settings:/app/settings/:rw
      - /var/run/docker.sock:/var/run/docker.sock
    # image: assaro/ddbot:latest
    # image: anshuljkt1/dd-bot-advanced:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped